version: '3.8'

services:
  react-app:
    image: yuseon7129/peachpitch:frontend
    container_name: my-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - peachpitch-network

networks:
  peachpitch-network:
    external: true