version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pikapikapika1234
      MYSQL_DATABASE: test
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    networks:
      - my-network

volumes:
  mysql-data: