version: '3.1'

services:
  django-app:
    image: yuseon7129/peachpitch:bluegreen8083
    container_name: bluegreen-8083
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://43.201.5.129:13306/test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pikapikapika1234
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_REDIS_HOST=43.201.5.129
      - SPRING_REDIS_PORT=6379
    networks:
      - peachpitch-network
    ports:
      - "8083:8083"

networks:
  peachpitch-network:
    external: true
