version: '3.1'

services:
  api:
    image: yuseon7129/peachpitch:bluegreen8082
    container_name: bluegreen-8082
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8082
    ports:
      - '8082:8081'