version: '3.1'

services:
  api:
    image: yuseon7129/peachpitch:bluegreen8082
    container_name: bluegreen-8082
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://43.201.5.129:13306/test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pikapikapika1234
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    ports:
      - '8082:8081'

networks:
  bridge:
    external: true