version: '3.1'

services:
  api:
    image: yuseon7129/peachpitch:bluegreen8081
    container_name: bluegreen-8081
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8081
    ports:
      - '8081:8081'