version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://43.201.5.129:13306/test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pikapikapika1234
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    networks:
      - my-network
    # depends_on:
    #   - mysql
    #   - redis

networks:
  my-network:
    external: true
