# Generated by Django 4.2.19 on 2025-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingHabits',
            fields=[
                ('wordid', models.BigAutoField(db_column='wordId', primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'speaking_habits',
                'managed': False,
            },
        ),
    ]
