# Generated by Django 4.2.19 on 2025-02-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportAI', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeakingHabits',
        ),
    ]
