# Generated by Django 4.2.19 on 2025-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_time', models.IntegerField()),
                ('cons', models.CharField(max_length=300)),
                ('pros', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'chat_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
