# Generated by Django 4.2.19 on 2025-02-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportAI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='ChatReport',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
