# Generated by Django 4.2.19 on 2025-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportAI', '0002_delete_chat_delete_chathistory_delete_chatreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCharacter',
            fields=[
                ('ai_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ai_face_1', models.TextField(blank=True, null=True)),
                ('ai_face_2', models.TextField(blank=True, null=True)),
                ('ai_face_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_character',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('backgroundid', models.BigAutoField(db_column='backgroundId', primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'background',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('blacklist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_user_id', models.BigIntegerField()),
                ('to_user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'blacklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('userid', models.BigIntegerField(db_column='userId')),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('keyword1_id', models.BigIntegerField(blank=True, null=True)),
                ('keyword2_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user1_feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('user1_id', models.BigIntegerField()),
                ('user1_name', models.CharField(max_length=40)),
                ('user2_feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('user2_id', models.BigIntegerField(blank=True, null=True)),
                ('user2_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'chat_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_time', models.IntegerField()),
                ('cons', models.CharField(blank=True, max_length=300, null=True)),
                ('pros', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'chat_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Havecoupon',
            fields=[
                ('havecouponid', models.BigAutoField(db_column='haveCouponId', primary_key=True, serialize=False)),
                ('ea', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'havecoupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('hintid', models.BigAutoField(db_column='hintId', primary_key=True, serialize=False)),
                ('hint', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'hint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.BigAutoField(db_column='itemId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keywordid', models.BigAutoField(db_column='keywordId', primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=30, unique=True)),
                ('totalcount', models.IntegerField(blank=True, db_column='totalCount', null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('maskid', models.BigAutoField(db_column='maskId', primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mask',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseid', models.BigAutoField(db_column='purchaseId', primary_key=True, serialize=False)),
                ('ea', models.IntegerField()),
                ('method', models.CharField(max_length=255)),
                ('orderid', models.CharField(db_column='orderId', max_length=255)),
                ('paymenttime', models.DateTimeField(db_column='paymentTime')),
                ('totalprice', models.IntegerField(db_column='totalPrice')),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('refreshid', models.BigAutoField(db_column='refreshId', primary_key=True, serialize=False)),
                ('expiration', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh', models.CharField(blank=True, max_length=255, null=True)),
                ('useremail', models.CharField(blank=True, db_column='userEmail', max_length=255, null=True)),
            ],
            options={
                'db_table': 'refresh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakingHabits',
            fields=[
                ('wordid', models.BigAutoField(db_column='wordId', primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'speaking_habits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalreport',
            fields=[
                ('totalreportid', models.BigAutoField(db_column='totalReportId', primary_key=True, serialize=False)),
                ('anscount', models.IntegerField(blank=True, db_column='ansCount', null=True)),
                ('questcount', models.IntegerField(blank=True, db_column='questCount', null=True)),
                ('totalchattime', models.IntegerField(blank=True, db_column='totalChatTime', null=True)),
            ],
            options={
                'db_table': 'totalreport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usedcoupon',
            fields=[
                ('couponid', models.BigAutoField(db_column='couponId', primary_key=True, serialize=False)),
                ('useddate', models.DateField(db_column='usedDate')),
            ],
            options={
                'db_table': 'usedcoupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.BigAutoField(db_column='userId', primary_key=True, serialize=False)),
                ('birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('snsid', models.CharField(blank=True, db_column='snsId', max_length=40, null=True)),
                ('snstype', models.CharField(blank=True, db_column='snsType', max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userkeyword',
            fields=[
                ('selectedid', models.BigAutoField(db_column='selectedId', primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userkeyword',
                'managed': False,
            },
        ),
    ]
