# Generated by Django 4.2.19 on 2025-02-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportAI', '0004_delete_speakinghabits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingHabits',
            fields=[
                ('word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'speaking_habits',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AiCharacter',
        ),
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.AlterModelTable(
            name='havecoupon',
            table='have_coupon',
        ),
        migrations.AlterModelTable(
            name='totalreport',
            table='total_report',
        ),
        migrations.AlterModelTable(
            name='usedcoupon',
            table='used_coupon',
        ),
        migrations.AlterModelTable(
            name='userkeyword',
            table='user_keyword',
        ),
    ]
