version: '3.1'

services:
  springboot-app:
    image: yuseon7129/peachpitch:bluegreen8081
    container_name: bluegreen-8081
    build:
      context: .
      dockerfile: Dockerfile8081
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR:ko
      - LC_ALL=ko_KR.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://43.201.5.129:13306/peachpitch?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pikapikapika1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081
      - SPRING_REDIS_HOST=43.201.5.129
      - SPRING_REDIS_PORT=6379
    networks:
      - peachpitch-network
    ports:
      - "8081:8081"

networks:
  peachpitch-network:
    external: true