spring:
  data:
    redis:
      host: 43.201.5.129
      port: 6379
  datasource:
    url: jdbc:mysql://43.201.5.129:13306/peachpitch?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: pikapikapika1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: Backend
    
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
  port: 8081

