version: '3.1'

services:
  django-app:
    image: yuseon7129/peachpitch:bluegreen8083
    container_name: bluegreen-8083
    build:
      context: .
      dockerfile: Dockerfile8083
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR:ko
      - LC_ALL=ko_KR.UTF-8
      - DJANGO_DATASOURCE_URL=jdbc:mysql://43.201.5.129:13306/peachpitch?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - DJANGO_DATASOURCE_USERNAME=root
      - DJANGO_DATASOURCE_PASSWORD=pikapikapika1234
      - DJANGO_JPA_HIBERNATE_DDL-AUTO=update
      - DJANGO_PORT=8083
      - DJANGO_REDIS_HOST=43.201.5.129
      - DJANGO_REDIS_PORT=6379
    networks:
      - peachpitch-network
    ports:
      - "8083:8083"

networks:
  peachpitch-network:
    external: true
